# Generated by Django 4.1.4 on 2022-12-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='Cedula',
            new_name='cedula',
        ),
    ]
