# Generated by Django 4.1.4 on 2022-12-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_rename_cedula_clients_cedula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Clientes',
        ),
    ]
