# Generated by Django 4.1.4 on 2022-12-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_clients_delete_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
