# Generated by Django 4.1.4 on 2022-12-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_tablaprueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
