# Generated by Django 4.1.4 on 2022-12-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_delete_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TablaPrueba',
        ),
    ]
