# Generated by Django 4.1.4 on 2022-12-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_tablaclientes_delete_tablaprueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaNueva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TablaClientes',
        ),
    ]
