# Generated by Django 4.1.4 on 2022-12-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_tablapeliculas_delete_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablanueva',
            name='lastName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
